---
apiVersion: v1
data:
  htpasswd: dXNlcjE6JDJ5JDA1JFBqUWVqZ1VNMzU5LnJkOE5xQzlweXVHbk9JM3JrVWl4cWh2NDg4enJVNVJvaEhZa2dLWGFhCg==
kind: Secret
metadata:
  name: htpass-secret
  namespace: openshift-config
type: Opaque

